import { writeFile } from "node:fs/promises";
import path from "node:path";
import { discoverScenarios } from "../src/prompts/discover";

function formatUnion(values: string[]): string {
        if (values.length === 0) {
                return "never";
        }

        return values.map((value) => `"${value}"`).join("\n        | ");
}

async function writeScenarioTypes(scenarios: string[]) {
        const sorted = [...scenarios].sort();
        const content = `// AUTO-GENERATED BY scripts/generate-scenarios.ts. DO NOT EDIT.
// Run \"npm run generate:scenarios\" to update this file.

export type ScenarioId =
        ${formatUnion(sorted)};
`;
        const targetPath = path.resolve(__dirname, "../src/types/generated-scenarios.ts");
        await writeFile(targetPath, content, "utf8");
}

async function writeDiscoveredScenarios(
        scenarios: ReturnType<typeof discoverScenarios>,
) {
        const sorted = [...scenarios].sort((a, b) => a.id.localeCompare(b.id));
        const entries = sorted
                .map(
                        (scenario) =>
                                `        { id: "${scenario.id}", tier: "${scenario.tier}", markdown: ${JSON.stringify(scenario.markdown)} },`,
                )
                .join("\n");

        const content = `// AUTO-GENERATED BY scripts/generate-scenarios.ts. DO NOT EDIT.
// Run \"npm run generate:scenarios\" to update this file.

import type { ScenarioTier } from "../types/scenarios";
import type { ScenarioId } from "../types/generated-scenarios";

export interface DiscoveredScenarioData {
        id: ScenarioId;
        tier: ScenarioTier;
        markdown: string;
}

export const DISCOVERED_SCENARIOS: DiscoveredScenarioData[] = [
${entries}
];
`;

        const targetPath = path.resolve(__dirname, "../src/prompts/generated-scenarios.ts");
        await writeFile(targetPath, content, "utf8");
}

async function main() {
        const discovered = discoverScenarios();
        await writeScenarioTypes(discovered.map((scenario) => scenario.id));
        await writeDiscoveredScenarios(discovered);
}

void main();
